---
openapi: 3.0.0
info:
  title: 'Relaxdays Hackathon Example '
  description: |-
    This is the swagger api.

    https://github.com/Garados007/RelaxHackathon.NthPrime
  termsOfService: http://swagger.io/terms/
  license:
    name: MIT
    url: https://github.com/Garados007/RelaxHackathon.NthPrime/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Garados007/Relaxday-Hackathon-Example-49/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost/
paths:
  /n-th-prime/:
    get:
      summary: returns the n-th prime
      parameters:
      - name: "n"
        in: query
        description: the number n
        required: true
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          example: 200
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
    post:
      summary: returns the n-th prime
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_1'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
components:
  schemas:
    n-th-prime:
      type: object
      properties:
        id:
          type: integer
          format: int64
    inline_response_200:
      example: 1223
      oneOf:
      - type: integer
      - type: string
    body:
      type: object
      properties:
        n:
          minimum: 1
          type: integer
          description: the value n
          example: 200
    body_1:
      type: object
      properties:
        n:
          minimum: 1
          type: integer
          description: the value n
          example: 200
  requestBodies: {}
  securitySchemes: {}
